{application,exgb,
             [{registered,[]},
              {description,"An xgboost library for Erlang"},
              {vsn,"0.0.3"},
              {applications,
               [kernel,
                stdlib]},
              {modules, ['exgb','exgb_srv']},
              {env,[]},
              {mod,{exgb,[]}}]}.
